### ISSUE TITLE
gganimate instal fails

### ISSUE THREAD

**Issue by dinrao** [thomasp85/gganimate#173]
Hi I'm trying to install gganimate on R (ver 3.3.3) on a Mac (Sierra) . I get this error message ERROR: dependencies 'glue', 'progress', 'gifski' are not available for package 'gganimate'. Can you help me troubleshoot this?

**Comment by bradlindblad** [comment]
Yes, this failed for me too on WIndows 10.

ERROR: dependency 'farver' is not available for package 'tweenr'
* removing 'C:/Users/lindblb/Documents/R/R-3.5.1/library/tweenr'
In R CMD INSTALL

ERROR: dependency 'tweenr' is not available for package 'gganimate'
* removing 'C:/Users/lindblb/Documents/R/R-3.5.1/library/gganimate'
In R CMD INSTALL

Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'farver'
* removing 'C:/Users/lindblb/Documents/R/R-3.5.1/library/farver'
In R CMD INSTALL

**Comment by schnarrd** [comment]
I also had an installation issue, but on Windows 7.  I read through this thread (https://github.com/thomasp85/gganimate/issues/115), which seemed to indicate that I need to install Rtools to install gganimate.  I did so and was able to successfully find Rtools using pkgbuild::find_rtools().  However, I got the following notice:

![image](https://user-images.githubusercontent.com/5552513/45579828-8569d480-b850-11e8-9f6f-d2b53f84e410.png)

Followed by this if I select "Yes"

![image](https://user-images.githubusercontent.com/5552513/45579866-d5e13200-b850-11e8-9662-4706f647d0dc.png)

It looks like tweenr is causing the error, but as shown in the first screenshot, I'm unable to install tweenr separately from gganimate.  I'm not sure what to do from here.

**Comment by thomasp85** [comment]
@dinrao for your issue you should simply install these packages on your mac... for @bradlindblad and @schnarrd it appears you are two of the many who have trouble getting RTools to work with R 3.5.1 on windows. This is not related to gganimate
